### PR TITLE
Full change of the image if pointing necessary

### PR DESCRIPTION
**Pull request by ANaaim**
linked to #45  (was closed but I think some rework might improve the code)

I was not totally satisfied with only removing the number and felt that removing also ... everything was maybe easier for pointing. 

This is a proposition of modification. Tell me what you think about it.

### CODE REVIEW

**Comment by davidpagnon** [comment]
Concerning this, I am just afraid that it may make it harder for people to remember in which order the points need to be clicked. What is the reason for removing everything, do these 4 numbers take up too much space on your image?

**Comment by ANaaim** [comment]
Not really the numbers, but all the other stuff(the cross the colour line etc...) . Maybe we can go on something lighter. For example before the pointing we can add the image of a checkerboard with the correct order of the pointing. Instead of just showing the point on a new matplotlib images when it is a checkerboard we show a generic image of how the checkerboard should be labelle. But nothing should be above the checkerboard on the image when we do the pointing elsewhere we cannot point correctly I think. => could be great if we can point at the same time as the images ois there) 

Tell me what you think about it.

**Comment by davidpagnon** [comment]
I am not sure I understand the last sentence, what do you mean by "pointing at the same time the image is there"?

Now that I think about it, until I understand better your answer, the change you made might be good the way it is :)

**Comment by ANaaim** [comment]
In short, when you are trying to point a checkerboard with the option C everything would be remove from the image where the pointing is done but we would generate a 2nd image in parrallel showing a 2D checkerboard (with the same size as the user is giving) showing the order of the pointing (with the number and the colorline to help remembering the order of pointing) ==> it would be also shown when no solution is found and would help the user better than only the point in 3D we are currently showing. 

==> I can add this feature to the branch. And we can also talk quickly about it during a call if you want :)

**Comment by ANaaim** [comment]
a figure like this (still some stuff to modify for readability but you got the idea):  

Figure_1

**Comment by davidpagnon** [comment]
I am not sure, what is the difference with this? (image from intrinsic calibration)
Is it not something you get when you hit C on extrinsic calibration with a board? 
image

Sorry I'm mostly available on weekends on this project but you surely have better things to do :D (aside from that I can make myself available anytime, you can easily find my number on the web)

**Comment by ANaaim** [comment]
It is in a way the same but imagine. But on mine we can add the proper order with info on where is the first corner to point (it should be near the most lateral dark corner) the order in which we should point it etc... => kind of a "how to point correctly the corner in order" from the one I drew we can add some text and better show the position of the first corner to point (this is a way to solve what you said about giving information to the user on how to point correctly but being able to remove any information on the image to point) 

When you know the rule for pointing this kind of stuff is pointless but could help beginner. As a user the current state of the explanation is enough for me.

**Comment by davidpagnon** [comment]
Okay I see! It won't make a very big difference but it could help some. 
Well I won't have time for it but if you feel like it, feel free to implement this! In the meantime I will merge your previous modification.

**Pull request merged**
