### PR TITLE
Save to c3d and convert trc to c3d

### PR DESCRIPTION
**Pull request by hunminkim98**
Hello Sir!
Sorry, I'm a bit late..!

This pull request is for trc to c3d converter.
 1. The function of trc_to_c3d would work directly through triangulation.py or filtering.
 2.  trc_to_c3d.py in the utilities folder would work independently with --flag commands.
 
Thanks for your great work as always!

### CODE REVIEW

**Comment by ANaaim** [comment]
Nice one... one of my colleague just came asking me if it would be possible to have a easy one for this. thanks @hunminkim98

**Comment by hunminkim98** [comment]
Thank you, @ANaaim !
I am not familiar with the structure of c3d files, so there may be some corrections needed (although there are no issues with my data). 
I hope this is useful for everyone. 
I also thanks for your work. 👍

**Comment by ANaaim** [comment]
In my lab we are using ezc3d to handle c3d. Very nice toolbox and efficient (based on C++) 

Might be interesting to use it! I might have a look at it to integrate it . 

Best regards

**Comment by hunminkim98** [comment]
I briefly looked into ezc3d, it seems very useful!
It is available through Python! If it integrates into Pose2Sim, should be useful for everyone!
Thank you for sharing!

Best regards.

**Comment by davidpagnon** [comment]
Hi @hunminkim98,

Great work! The script `Utilities/trc_to_c3d.py` is good, I've got nothing but good things to say about it.
Sorry for being a pest, there are a few issues that I found:

- first, now that I have made a few changes, there are conflicts to resolve. Fortunately, they are just in the Config.toml files, and you can take my last version
- then, I already had the option `make_c3d` at the end of [triangulation] in the configuration files. Could you use this rather than `save_to_c3d`? Actually, choose the one you prefer, it does not matter as long as there is only one.
- I had a final suggestion but upon thinking, I am not sure it is useful anymore. I was thinking that some users may want to create c3d files and do not care about trc files. In this case, it would be better to replace `trc_to_c3d()` in common.py by `make_c3d()`, which would directly take data points as input instead of trc files. But I'm not sure it is worth the pain anymore (probably not) and I need to sleep.  :D

**Comment by hunminkim98** [comment]
> Hi @hunminkim98,
> 
> Great work! The script `Utilities/trc_to_c3d.py` is good, I've got nothing but good things to say about it. Sorry for being a pest, there are a few issues that I found:
> 
> * first, now that I have made a few changes, there are conflicts to resolve. Fortunately, they are just in the Config.toml files, and you can take my last version
> * then, I already had the option `make_c3d` at the end of [triangulation] in the configuration files. Could you use this rather than `save_to_c3d`? Actually, choose the one you prefer, it does not matter as long as there is only one.
> * I had a final suggestion but upon thinking, I am not sure it is useful anymore. I was thinking that some users may want to create c3d files and do not care about trc files. In this case, it would be better to replace `trc_to_c3d()` in common.py by `make_c3d()`, which would directly take data points as input instead of trc files. But I'm not sure it is worth the pain anymore (probably not) and I need to sleep.  :D

Totally understood!
I missed the "make_c3d" option, I'll remove the "save_to_c3d"!
The last one, while it's more convenient for those who only want a .c3d file, I'll have to look into how to create a c3d file directly from the 3d coordinates of the triangulation. and I'll let you know!

**Comment by davidpagnon** [comment]
Then don't worry about it, at least for now, it is not a priority. I'll merge it as soon as the conflicts are solved and we can talk about small possible improvements later :)

**Comment by hunminkim98** [comment]
I'll update my folk repository to synchronize your last version.
To do that, this pull request will be closed.

**Pull request merged**
