### PR TITLE
Correction in list comprehension to allow the second term to be consider

### PR DESCRIPTION
**Pull request by ANaaim**

### CODE REVIEW

**Comment by ANaaim** [comment]
Hi, 

I think i found a small error in a list comprehension in your code : 
```python
    calib_dir = [os.path.join(project_dir, c) for c in os.listdir(project_dir) if ('Calib' or 'calib') in c][0]
```

Should be 
```python
    calib_dir = [os.path.join(project_dir, c) for c in os.listdir(project_dir) if ('Calib' in c or 'calib' in c)][0]
```

Elsewhere the second term is not taken into account : 

I tested with the following code to be sure : 


alpha = ['toto','tata','titi','tutu']
[c for c in alpha if ('tyty' or 'titi') in c]
Out[8]: []
[c for c in alpha if ('titi' or 'tyty') in c]
Out[9]: ['titi']
[c for c in alpha if ('titi' in c or 'tyty' in c)]
Out[10]: ['titi']
[c for c in alpha if ('tyty' in c or 'titi' in c)]
Out[11]: ['titi']

I hope it is correct.

Best regards,

**Comment by davidpagnon** [comment]
We will choose the second of your option, thanks!

**Comment by davidpagnon** [comment]
Oops wrong pull request

**Comment by davidpagnon** [comment]
Interesting, thanks!

**Pull request merged**
