### PR TITLE
implementing OpensimProcessing

### PR DESCRIPTION
**Pull request by peterlololsss**
Hi i think opensimProcessing should work now for single trial,  i haven't test it on batch though i doubt it would work, since i haven't quite figured out the logic behind reading keywords from diffenrent config depneds on which level the config is at.

If you encounter any issues please let me know! :)

### CODE REVIEW

**Comment by peterlololsss** [comment]
linked to issue#130

**Comment by davidpagnon** [comment]
Thank you Peter for your contribution! I definitely wanted to integrate the script I sent you but could not find time for it. 
I cannot test it right now, but here are a few pieces of feedback:
- There are some mismatches between the version you pushed and the last changes (see the red lines [there](https://github.com/perfanalytics/pose2sim/pull/130/files), especially concerning some comments in Config.toml and the logging.shutdown() in Pose2Sim.py.
- Could you try and make the formatting and docstrings consistent with the other Pose2Sim functions? (especially the explanations at the beginning of the file and the function docstrings)
- I think you tested Scaling and IK only on the Single Person Demo. Could you also try it on Demo_MultiPerson and Demo_Batch? Right now, it seems like [there is a syntax error](https://github.com/perfanalytics/pose2sim/actions/runs/10539553061/job/29225115245?pr=130) line 207 of scaling2IK.py
- Could you also edit [tests.py](https://github.com/perfanalytics/pose2sim/blob/main/Pose2Sim/Utilities/tests.py) so that the kinematics stage is also tested upon each push?
- Instead of using dictionaries, could you model, scaling and IK files directly from the model name? Feel free to rename BODY_25 to BODY25, HALPE_26 to HALPE26, etc (and reflect it in Readme.md)
- While we are at naming conventions, I actually don't think LSTM speaks to many people. Could we rename all the LSTM occurrences to "Augmented"? (in the OpenSim files and all the Config files as well)
- I would like to rename scaling2IK.py to kinematics.py. Feel free to differ if you do not think it is a good idea.
- It would be great if you could add a line in the Demonstration Part 1 section of Readme.md: `Pose2Sim.kinematics()`. You could add a link to section 2.v, named "if kinematic results are not convincing" (or something along this idea)

**Comment by davidpagnon** [comment]
**Explanation on choosing the best frames for scaling (L241-252):**
On difficult trials, some points are not well triangulated, which can lead to bad scaling. For example, if a point of the foot is very far from the rest of the body on some frames, scaling will consider that the foot is very large. Consequently, we need to scale only on the frames that are best triangulated. Now, how to find these best frames? 
  My reasoning was that the points of badly triangulated frames would go all over the place, and thus that their speeds would be fast. So I only selected the 10% slowest frames for scaling. I think that in addition, we should **take the median scale factor for these frames**, because we might have slow frames that are still bad. -> This last step has not been done.
  
It is quite possible that there is a better approach, so feel free to suggest anything else!
Lastly, if you don't know what to do with your time, feel free to test scaling and IK on challenging cases (like with only 2 cameras, a person exiting and reentering the field of capture, and challenging motion types).

**Comment by davidpagnon** [comment]
Related to this issue: https://github.com/perfanalytics/pose2sim/issues/129

**Pull request merged**
