### PR TITLE
Correction of the position of obj to be able to run extrinsic correction

### PR DESCRIPTION
**Pull request by ANaaim**
Linked to : #46 
Linked to : #48

### CODE REVIEW

**Comment by ANaaim** [comment]
I can add the correction of the unit in this PR if it is ok for you.

**Comment by davidpagnon** [comment]
Looking good, thanks!

**Comment by davidpagnon** [comment]
I may have merged changes a little fast concerning the first issue. To be honest, I haven't extensively tested extrinsic calibration with a checkerboard. 
Did you, and does it work? Does it also work if corners are correctly detected and you hit 'Y' instead of 'C'?

**Comment by ANaaim** [comment]
Normally, yes on my data the first camera has it checkerboard detected automatically and for the other I had to click so both the Y and C  were tested.

**Pull request merged**
